config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog_app.urls', namespace='blog_app')),
    path('user/', include('user_app.urls', namespace='user_app')),
]

user_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from django.views.generic import DetailView, View
from user_app import views as v
from django.views.decorators.cache import cache_page


app_name = 'user_app'

urlpatterns = [
    path('login_user/', v.UserLoginView.as_view(), name='login_user'),
    path('logout_user/', LogoutView.as_view(), name='logout_user'),
    path('register_user/', v.RegisterUserView.as_view(), name='register_user'),
    path('confirm_user/', v.ConfirmEmailView.as_view(), name='confirm_user'),
    path('reset_password/', v.reset_password, name='reset_password'),
    path('delete_avatar/', v.delete_avatar, name='delete_avatar'),
    path('update_user/', v.UpdateProfileView.as_view(), name='update_user'),
    path('profile_view/', cache_page(60*15)(v.ProfileView.as_view()), name='profile_view'),

]

user_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime
from django.utils.timezone import now

# Create your models here.

class User(AbstractUser):
    username = None
    email = models.CharField(verbose_name='', unique=True)
    avatar = models.ImageField(verbose_name='Аватарка', upload_to='media/users', blank=True, null=True)
    birthday = models.DateTimeField(verbose_name='Дата рождения', null=True, blank=True, default=None)
    phone_number = models.CharField(verbose_name='Номер телефона', max_length=12, blank=True, null=True)
    country = models.CharField(verbose_name='Страна', max_length=50, blank=True, null=True)
    temporary_password = models.CharField(verbose_name='Temporary password', max_length=6, blank=True, null=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

user_app/forms.py
from django import forms as f
from django.contrib.auth import forms
from django.contrib.auth import get_user_model


class UserLoginForm(forms.AuthenticationForm):
    username = f.CharField(max_length=50, label='E-mail', widget=f.TextInput(attrs={'class': 'auth-fields'}))
    password = f.CharField(max_length=50, label='Пароль', widget=f.PasswordInput(attrs={'class': 'auth-fields'}))

    class Meta:
        model = get_user_model()
        fields = '__all__'


class UserRegistrationForm(forms.UserCreationForm):
    email = f.CharField(label='E-mail', widget=f.EmailInput(attrs={'class': 'register-fields'}))
    password1 = f.CharField(max_length=255, label='Пароль', widget=f.PasswordInput(attrs={'class': 'register-fields'}))
    password2 = f.CharField(max_length=255, label='Повтор пароля', widget=f.PasswordInput(attrs={'class': 'register-fields'}))
    avatar = f.ImageField(label='Аватар', widget=f.FileInput(attrs={'class': 'register-fields'}), required=False)
    birthday = f.DateField(label='Дата рождения', widget=f.DateInput(attrs={'class': 'register-fields'}), required=False)
    phone_number = f.CharField(label='Номер телефона', max_length=12, widget=f.TextInput(attrs={'class': 'register-fields'}), required=False)
    country = f.CharField(label='Страна', max_length=50, widget=f.TextInput(attrs={'class': 'register-fields'}), required=False)

    class Meta:
        model = get_user_model()
        fields = [
            'email',
            'password1',
            'password2',
            'first_name',
            'last_name'
        ]

        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }

        widgets = {
            'email': f.EmailInput(attrs={'class': 'register-fields'}),
            'first_name': f.TextInput(attrs={'class': 'register-fields'}),
            'last_name': f.TextInput(attrs={'class': 'register-fields'}),
        }
    
    def clean_password(self):
        data = self.cleaned_data
        if data['password1'] != data['password2']:
            raise f.ValidationError('Пароли не совпадают!')    
        return data['password']
    
    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise f.ValidationError('Этот эмейл уже используется!')
        return email


class UserConfirmForm(f.ModelForm):
    temporary_password = f.CharField(max_length=6, label='Временный пароль', widget=f.TextInput(attrs={'class': 'register-fields'}))

    class Meta:
        model = get_user_model()
        fields = ['temporary_password',]


class UserEditForm(f.ModelForm):
    avatar = f.ImageField(label='Аватар', widget=f.FileInput(attrs={'class': 'register-fields'}), required=False)
    birthday = f.DateField(label='Дата рождения', widget=f.DateInput(attrs={'class': 'register-fields'}), required=False)
    phone_number = f.CharField(label='Номер телефона', max_length=12, widget=f.TextInput(attrs={'class': 'register-fields'}), required=False)
    country = f.CharField(label='Страна', max_length=50, widget=f.TextInput(attrs={'class': 'register-fields'}), required=False)

    class Meta:
        model = get_user_model()
        fields = [
            'first_name',
            'last_name',
            'avatar',
            'phone_number',
            'birthday',
            'country'
        ]

        widgets = {
            'first_name': f.TextInput(attrs={'class': 'register-fields'}),
            'last_name': f.TextInput(attrs={'class': 'register-fields'}),
        }

user_app/views.py
from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import views as v
from django.contrib.auth import forms as f
from django.urls import reverse_lazy

from config import settings
from user_app.models import User
from .forms import UserConfirmForm, UserEditForm, UserLoginForm
from django.views import generic as g
from django.contrib.auth import get_user_model
from .forms import UserRegistrationForm

import os
from django.core.mail import send_mail
from django.utils.crypto import get_random_string

current_email = None

# Create your views here.

class UserLoginView(v.LoginView):
    form_class = UserLoginForm
    template_name = 'user_app/user_auth.html'


class RegisterUserView(g.FormView):
    form_class = UserRegistrationForm
    template_name = 'user_app/user_register.html'
    success_url = reverse_lazy('user_app:confirm_user')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_edit'] = False
        return context
    

    def form_valid(self, form):
        global current_email

        secret_code = get_random_string(length=6)
        user = form.save()
        user.is_active = False
        user.set_password(form.cleaned_data['password1'])
        user.temporary_password = secret_code
        user.birthday = form.cleaned_data['birthday']
        user.phone_number = form.cleaned_data['phone_number']
        user.country = form.cleaned_data['country']
        current_email = user.email

        my_user = form.save()
        send_mail(
            subject='Подтверждение почты',
            message=f'Для продолжения регистрации введите этот код в окне регистрации\n{secret_code}',
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[f'{my_user.email}',]
        )

        return super().form_valid(form)


class UpdateProfileView(g.UpdateView):
    model = get_user_model()
    form_class = UserEditForm
    template_name = 'user_app/user_register.html'
    success_url = reverse_lazy('user_app:profile_view')
    context_object_name = 'context'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_edit'] = True
        return context

    def get_object(self, queryset=None):
        return self.request.user


class ProfileView(g.TemplateView):
    model = get_user_model()
    template_name = 'user_app/user_view.html'
    context_object_name = 'context'
    
    def get_object(self, queryset=None):
        return self.request.user


def reset_password(request):
    new_password = get_random_string(length=10)
    email = request.user.email
    send_mail(
            subject='Новый пароль',
            message=f'Новый пароль для пользователя {email}\n"{new_password}"',
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[f'{email}',]
        )
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse_lazy('user_app:login_user'))


class ConfirmEmailView(g.FormView):
    template_name = 'user_app/user_confirm.html'
    form_class = UserConfirmForm
    success_url = reverse_lazy('user_app:login_user')
    global current_email

    def form_valid(self, form):
        temp_password_f = form.cleaned_data['temporary_password']
        user = User.objects.get(email=current_email)

        temp_password_u = user.temporary_password
        print(temp_password_f, temp_password_u)

        if temp_password_u == temp_password_f:
            user.is_active = True
            user.save()
            return super().form_valid(form)
        else:
            return super().form_invalid(form)


def delete_avatar(request):
    request.user.avatar = None
    request.user.save()
    return redirect(reverse_lazy('user_app:update_user'))

user_app/templates/user_app/user_auth.html
{% extends 'catalog/base.html' %}


{% block content %}
{% load static %}

<h1 style="position: relative; left: 40%;">Добро пожаловать!</h1>
<p style="font-size: 7mm; position: relative; top: 5mm; left: 25%;">
    Для авторизации, пожалуйста, введите ваши логин (или емейл) и пароль.
</p>
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}">
    <div class="col-3" style="position: relative; left: 185mm; top: 15mm;">

        {% for f in form %}
        <div class="row">
            <div class="col"><label for="{{ f.id_for_label }}">{{ f.label.title }}</label></div>
            <div class="col">{{ f }}</div>
        </div>
        <div class="form-error mb-2 text-center" style="font-size: 6mm; color: brown;">{{ f.errors}}</div>
        {% endfor %}

        <button type="submit" class="btn btn-outline-success" style="position: relative; left: 38%; top: 1cm;">Войти</button>
        
    </div>
</form>



{% endblock content %}

user_app/templates/user_app/user_confirm.html
{% extends 'catalog/base.html' %}


{% block content %}
{% load static %}
    <h1 style="display: grid; place-items: center;">Подтверждение почты</h1>
    <div class="col">
        <p class="col-6" style="position: relative; left: 25%; top: 8mm; font-size: 5mm;">
            Для завершения регистрации, пожалуйста, перейдите в указанынй вами почтовый ящик и введите секретный код из письма в форму ниже
        </p>
        <form method="post">
            {% csrf_token %}
            <div style="position: relative; left: 43%; top: 10mm;">
                <div class="row" style="font-size: 7mm;">
                    <label for="{{ form.temporary_password.id_for_label }}">{{ form.temporary_password.label.title }}</label>
                </div>
                <div class="row" style="position: relative; left: 3mm;">
                    {{ form.temporary_password }}
                </div>
                <div class="row" style="position: relative; left: 60px; top: 8mm;">
                    <button type="submit" class="btn btn-success">Подтвердить</button>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}
    

user_app/templates/user_app/user_register.html
{% extends 'catalog/base.html' %}


{% block content %}
{% load static %}
    
    {% if is_edit %}
        <h1 style="text-align: center;">Регистрация нового пользователя</h1>
    {% else %}
        <h1 style="text-align: center;">Изменить данные пользователя</h1>
    {% endif %}
        
    
    <div class="col" style="display: grid; place-items: center; top: 1cm;"> 
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for f in form %}
                <div class="row">
                    <div class="col"><label for="{{ f.id_for_label }}">{{ f.label.title }}</label></div>
                    <div class="col">{{ f }}</div>
                </div>
                <div class="form-error mb-2 text-center" style="font-size: 6mm; color: brown;">{{ f.errors}}</div>
            {% endfor %}
            
            {% if is_active %}            
                <button type="submit" class="btn btn-outline-success" style="position: relative; top: 1cm;">Зарегистрировать</button>
            {% else %}
            
            {% if is_edit %}
                <div class="row">
                    <div  class="col">
                        <a type="submit" class="btn btn-outline-danger" href="{% url 'user_app:delete_avatar' %}">Удалить автар</a>
                    </div>
                    <div class="col">
                        <a href="{% url 'user_app:reset_password' %}" class="btn btn-outline-danger">Изменить пароль</a></div>
                </div>
                <div class="row" style="position: relative; left: 43mm; top: 5mm">
                    <button type="submit" class="btn btn-outline-success" >Изменить</button>
                </div>
            {% else %}
                <div class="row" style="position: relative; left: 43mm; top: 5mm">
                    <button type="submit" class="btn btn-outline-success" >Зарегистрировать</button>
                </div>
            {% endif %}
                
                
                    
                
            {% endif %}
            
                
        </form>
    </div>
{% endblock content %}

user_app/templates/user_app/user_registration_done.html
{% extends 'catalog/base.html' %}


{% block content %}
    <h1 style="display: grid; place-items: center;">Добро пожаловать на сайт</h1>
{% endblock content %}
    

user_app/templates/user_app/user_view.html
{% extends 'catalog/base.html' %}


{% block content %}
{% load mediapath %}
{% load static %}

<div style="display: grid; place-items: center;">
    <div>       

        {% if user.avatar %}
            <img src="{{ user.avatar.url }} " alt="Нет аватарки">
        {% else %}
            <img src="../../../media/anonim.jpg" style="width: 8cm; height: 8cm;" alt="Нет аватарки">
        {% endif %}
    </div>
    <h1 style="position: relative; top: 1cm;">Профиль пользователя </h1>
    <div class="col-6" style="display: grid; place-items: left; position: relative; top: 1cm">
        <div class="row" style="font-size: 7mm;">{{ user.first_name }} {{ user.last_name }}</div>
        <div class="row" style="font-size: 7mm;">{{ user.email }}</div>
        <div class="row" style="font-size: 7mm;">{{ user.birthday }}</div>
        <div class="row" style="font-size: 7mm;">{{ user.phone_number }}</div>
        <div class="row" style="font-size: 7mm;">{{ user.country }}</div>
    </div>
    <div style="position: relative; top: 15mm;"><a href="{% url 'user_app:update_user' %}">Редактировать профиль</a></div>
    
</div>
{% endblock content %}
    