blog_app/urls.py
from django.urls import path
from blog_app.apps import BlogAppConfig
from blog_app import views as v

app_name = BlogAppConfig.name


urlpatterns = [
    path('all_posts/', v.PostsListView.as_view() , name='all_posts'),
    path('create/', v.PostCreateView.as_view(), name='create'),
    path('<int:pk>/view/', v.PostDetailView.as_view() , name='view'),
    path('<int:pk>/edit/', v.PostUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', v.PostDeleteView.as_view() , name='delete'),
    path('<int:pk>/change_publish_status/', v.change_publish_status, name='change_publish_status'),


]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog_app.urls', namespace='blog_app')),
    path('user/', include('user_app.urls', namespace='user_app')),
]

blog_app/models.py
from django.contrib.auth import get_user_model
from django.db import models

from catalog.models import NULLABLE

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=50, verbose_name="Заголовок")
    slug = models.CharField(max_length=100, verbose_name="Slug")
    content = models.TextField(verbose_name="Содержимое")
    preview = models.ImageField(verbose_name="Превью", upload_to="catalog/media", null=True, blank=True)
    creation_date = models.DateField(auto_now=True, verbose_name="Дата сощдания")
    is_published = models.BooleanField(default=True, verbose_name="Статус публикации")
    views_counter = models.IntegerField(verbose_name="Счетчик просморов", default=0)
    author = models.ForeignKey(to=get_user_model(), on_delete=models.SET_NULL, **NULLABLE)
    
    def __str__(self) -> str:
        return f"Запись {self.title} с количеством просмотров - {self.views_counter}"
    
    class Meta:
        verbose_name = "Блог для сайта"
        verbose_name_plural = "Блоги для сайта"

blog_app/forms.py
from django import forms as f
from blog_app import models as m


class BlogCreateForm(f.ModelForm):
    title = f.CharField(label='Заголовок', widget=f.TextInput(attrs={'class': 'my-same-widht'}))
    content = f.CharField(label='Содержимое', widget=f.Textarea(attrs={'class': 'my-big-textarea'}))
    preview = f.ImageField(label='Превью', required=False, widget=f.FileInput(attrs={'class': 'my-same-widht'}))
    is_published = f.BooleanField(label='Статус публикации',widget=f.CheckboxInput(attrs={'class': 'my-checkbox'}))

    class Meta:
        model = m.Blog
        fields = ['title', 'content', 'preview', 'is_published']

blog_app/views.py
from typing import Any
from django.db import models
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views import generic as g

from blog_app import models
from blog_app import forms as f

from my_util_files.transcrypter import transcription

from django.contrib.auth import mixins
from django.contrib.auth import decorators as d

# Create your views here.

class PostsListView(g.ListView):
    model = models.Blog
    template_name = 'blog_app/posts_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        user = self.request.user
        if user.is_authenticated:
            if user.is_staff or user.is_superuser or user.has_perm('blog_app.change_blog'):
                pass
            else:
                queryset = queryset.filter(is_published=True).order_by('views_counter').reverse() | queryset.filter(author=user).order_by('views_counter').reverse()
        else:
            queryset = queryset.filter(is_published=True).order_by('views_counter').reverse()
        return queryset


class PostCreateView(mixins.LoginRequiredMixin, g.CreateView):
    model = models.Blog
    template_name = 'blog_app/post_create.html'
    form_class = f.BlogCreateForm
    success_url = reverse_lazy('blog_app:all_posts')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["editing"] = False
        return context

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = transcription(new_post.title)
            new_post.save()

            w = form.save(commit=False)
            w.author = self.request.user
        return super().form_valid(form)
    

class PostUpdateView(mixins.LoginRequiredMixin, g.UpdateView):
    model = models.Blog
    template_name = "blog_app/post_create.html"
    form_class = f.BlogCreateForm
    success_url = reverse_lazy('blog_app:all_posts')

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset.filter(pk = self.kwargs['pk'])
        return queryset   

    def get_success_url(self) -> str:
        return reverse('blog_app:view', args=[self.kwargs.get('pk')])

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = transcription(new_post.title)
            new_post.save()
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["editing"] = True
        return context


class PostDetailView(g.DeleteView):
    model = models.Blog
    template_name = "blog_app/post_view.html"
    context_object_name = 'post_data'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset.filter(pk=self.kwargs["pk"])
        return queryset
    
    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()
        return self.object

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post = transcription(new_post.title)
            print(new_post)
            new_post.save()
        return super().form_valid(form)


class PostDeleteView(mixins.LoginRequiredMixin, g.DeleteView):
    model = models.Blog
    template_name = "blog_app/post_delete.html"
    context_object_name = 'post_data'
    success_url = reverse_lazy('blog_app:all_posts')

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset.filter(pk=self.kwargs["pk"])
        return queryset


@d.permission_required('blog_app.publish_change_blog')
def change_publish_status(requesr, pk):
    blog = get_object_or_404(models.Blog, pk=pk)    
    if blog.is_published == True:
        blog.is_published = False
    else:
        blog.is_published = True
    blog.save()
    return redirect(reverse('blog_app:all_posts'))

blog_app/templates/blog_app/post_create.html
{% extends 'catalog/base_without_hat.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet"  type="text/css" href="{% static 'css/my_styles.css' %}">
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-12 md-4 mb-2">
        {% for f in form %}
        <div class="row">
            <div class="col" style="font-size: 6mm;"><label for="f.id_for_label">{{ f.label }}</label></div>
            <div class="col">{{ f }}</div>
        </div>
        {% endfor %}
            
        <div class="md-4 mb-4">
        {% if editing %}
            <button type="submit" class="btn btn-primary" enp>Изменить запись</button>
        {% else %}
            <button type="submit" class="btn btn-primary" enp>Добавить запись</button>
        {% endif %}
        </div>
    </div>
    </form>

    <!-- <div class="mb-5">
        <label for="exampleFormControlInput1" class="form-label">Название</label>
        <input class="form-control form-control-lg" type="text"
            placeholder="Название" aria-label=".form-control-lg example">
    </div>
    <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Описание</label>
        <textarea class="form-control" placeholder="Описание" id="exampleFormControlTextarea1" rows="3"></textarea>
    </div>
    <div class="mb-3">
        <label for="formFile" class="form-label">Выберите превью</label>
        <input class="form-control" type="file" id="formFile">
    </div> -->
</div>

{% endblock content %}

blog_app/templates/blog_app/post_delete.html
{% extends 'catalog/base_without_hat.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    <div class="col">
        <div class="container justify-content-center">
            <h2 align="center">Вы, действительно, хотите удалить запись?</h2>
            <div align="center"><h5>{{ post_data.title }}</h5></div>
            <h1> </h1>
        </div>
    </div>
    {{ form }}
    <div class="container text-center">
        <div class="row justify-content-center">
            <input type="submit" class="btn btn-outline-danger"
                value="Подтвердить">
            <a type="button" class="btn btn-outline-success"
                href="{% url 'blog_app:all_posts' %}">Отменить</a>
        </div>
    </div>
</form>

{% endblock content %}

blog_app/templates/blog_app/post_view.html
{% extends 'catalog/base_without_hat.html' %}

{% block content %}
{% load paragrapher %}

<div class="col-3">
    <a type="button" class="btn btn-outline-success"
        href="{% url 'blog_app:all_posts' %}">Вернуться к просмотру</a>
</div>
<div class="container text-left">
    <div class="col">
        <div class="card-title">
            <div align="center"> <h3>{{ post_data.title }}</h3> </div>
        </div>
        <div class="card-body">
            <div style="font-style: italic; font-size: 5mm;">
            {% if post_data.author %}
                <div class="row">{{post_data.author}}</div>
            {% else %}
                <div class="row">Автор неизвестен</div>
            {% endif %}
            </div>
            
            {% autoescape off %}            
            <div style="font-size: 6mm;">{{ post_data.content|paragrapher }}</div>   
            {% endautoescape %}        
        </div>
    </div>
</div>

<div class="col-12">
    <div class="col-2">
        <div><h5>Количество просмотров: {{ post_data.views_counter }}</h5></div>
    </div>
    <div class="col-6"><h5>Слаг для этой записи: {{ post_data.slug }}</h5></div>
</div>

{% endblock content %}

blog_app/templates/blog_app/posts_list.html
{% extends 'catalog/base.html' %}

{% block content %}
{% load mediapath %}

<ul class="nav justify-content-center">
    {% if user.is_authenticated %}
        <div style="display: grid; place-items: center;">
            <a class="nav-link" class="btn btn-success" href="{% url 'blog_app:create' %}">Добавить запись</a>
        </div>
    {% endif %}
</ul>

<h3 align="center">Здоровье в еде!</h3>
<div class="album">
    <div class="container text-center">
        <div class="row row row-cols-1">
            {% for card in object_list %}
            <div class="col md-3 mb-3">
                <div class="card" style="width: 20rem; height: 30rem;">
                    
                    {% if card.preview %}
                        <img src="{% mediapath card.preview %}" style="height: 250px; width: auto;" class="card-img-top"
                        alt="Превью">
                    {% else %}
                        <img src="../../../media/without_picture.jpg" style="height: 250px; width: auto;" class="card-img-top"
                        alt="Превью">
                    {% endif %}
                        
                    
                    <div class="card-body">
                        <h5 class="card-title">{{ card.title }}</h5>
                        <p class="card-text">{{ card.content|truncatechars:60 }}</p>
                        
                    </div>
                    <div style="position: relative; bottom: 10px;">
                        
                        {% if user.is_authenticated %}
                            <a href="{% url 'blog_app:view' card.pk %}" class="btn btn-primary">Читать</a>
                            
                            {% if card.author|stringformat:"s" == user.email|stringformat:"s" %}
                                <a href="{% url 'blog_app:edit' card.pk %}"class="btn btn-primary">Изменить</a>
                                <a href="{% url 'blog_app:delete' card.pk %}"class="btn btn-danger">Удалить</a>
                            {% elif perms.blog_app.change_blog %}
                                {% if card.is_published %}
                                    <a href="{% url 'blog_app:change_publish_status' card.pk %}"class="btn btn-primary">Снять с публикации</a>
                                {% else %}
                                    <a href="{% url 'blog_app:change_publish_status' card.pk %}"class="btn btn-primary">Вернуть в публикацию</a>
                                {% endif %}
                            {% endif %}
                                
                            
                        {% else %}
                            <a href="{% url 'blog_app:view' card.pk %}" class="btn btn-primary">Читать</a>
                        {% endif %}
                            
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}