blog_app/urls.py
from django.urls import path
from blog_app.apps import BlogAppConfig
from blog_app import views as v

app_name = BlogAppConfig.name


urlpatterns = [
    path('all_posts/', v.PostsListView.as_view() , name='all_posts'),
    path('create/', v.PostCreateView.as_view(), name='create'),
    path('<int:pk>/view/', v.PostDetailView.as_view() , name='view'),
    path('<int:pk>/edit/', v.PostUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', v.PostDeleteView.as_view() , name='delete'),
    path('<int:pk>/change_publish_status/', v.change_publish_status, name='change_publish_status'),


]

catalog/urls.py
from django.urls import path
from catalog import views as v
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from catalog.apps import CatalogConfig

app_name = CatalogConfig.name


urlpatterns = [
        path('', v.HomeListView.as_view(), name="home"),
        path('contacts/', v.ContactsCreateView.as_view(), name="contacts"),
        path('<int:pk>/product1/', v.ProductCardView.as_view(), name="product"),
        path('create_product/', v.ProductCreateView.as_view(), name="create_product"),
        path('update_product_<int:pk>/', v.ProductUpdateView.as_view(), name="update_product"),
        path('active_versions', v.ActiveVersionsListView.as_view(), name='active_versions'),
        path('delete_product_<int:pk>/', v.ProductDeleteView.as_view(), name='delete_product'),
        path('change_publish_status_<int:pk>/', v.change_publish_status, name='change_publish_status'),
        path('moderator_update_product_<int:pk>/', v.ModeratorUpdateProduct.as_view(), name="moderator_update_product"),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog_app.urls', namespace='blog_app')),
    path('user/', include('user_app.urls', namespace='user_app')),
]

user_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from django.views.generic import DetailView, View
from user_app import views as v
from django.views.decorators.cache import cache_page


app_name = 'user_app'

urlpatterns = [
    path('login_user/', v.UserLoginView.as_view(), name='login_user'),
    path('logout_user/', LogoutView.as_view(), name='logout_user'),
    path('register_user/', v.RegisterUserView.as_view(), name='register_user'),
    path('confirm_user/', v.ConfirmEmailView.as_view(), name='confirm_user'),
    path('reset_password/', v.reset_password, name='reset_password'),
    path('delete_avatar/', v.delete_avatar, name='delete_avatar'),
    path('update_user/', v.UpdateProfileView.as_view(), name='update_user'),
    path('profile_view/', cache_page(60*15)(v.ProfileView.as_view()), name='profile_view'),

]

catalog/models.py
from django.db import models
from django.contrib.auth import get_user_model

from user_app.models import User

NULLABLE = {
    "null": True,
    "blank": True
}


# Create your models here.

class Product(models.Model):
    title = models.CharField(max_length=20, verbose_name="Наименование", unique=True)
    description = models.TextField(verbose_name="Описание")
    image = models.ImageField(upload_to="catalog/media/", **NULLABLE, verbose_name="Изображние")
    category = models.ForeignKey(to='Category', verbose_name="Категория", **NULLABLE, on_delete=models.SET_NULL)
    price = models.FloatField(verbose_name="Цена за товар", **NULLABLE)
    creations_date = models.DateField(verbose_name="Дата создания", auto_created=True, auto_now_add=True)
    last_change_date = models.DateField(verbose_name="Дата последнего изменения", auto_now_add=True)
    version_of_product = models.ForeignKey(to='Version', **NULLABLE, on_delete=models.SET_NULL, verbose_name="Версия")
    author = models.ForeignKey(to=get_user_model(), **NULLABLE, on_delete=models.SET_NULL)
    is_published = models.BooleanField(verbose_name="Опубликовано ли?", default=True)

    def __str__(self):
        return f"{self.title} {self.category} {self.price}"

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"


class Category(models.Model):
    title = models.CharField(max_length=20, verbose_name="Наименование")
    description = models.TextField(verbose_name="Описание")

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Version(models.Model):
    product_name = models.ForeignKey(to='Product', to_field='title', on_delete=models.DO_NOTHING)
    version_number = models.FloatField(unique=True, verbose_name="Номер версии")
    version_title = models.CharField(max_length=100, verbose_name="Название версии")
    is_active_version = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"
    
    def __str__(self) -> str:
        if self.is_active_version is True:
            is_activated = "Активная версия"
        else:
            is_activated = "Не активная версия"

        return f'"{self.product_name}" - {self.version_number} - "{is_activated}"'

catalog/forms.py
from typing import Any
from django import forms as f
from .models import Product, Version
from .services import get_categories_queryset


class CreateProduct(f.ModelForm):
    title = f.CharField(label='Наименование', max_length=200, widget=f.TextInput(attrs={'class': 'my-same-widht'}))
    description = f.CharField(label='Описание', widget=f.Textarea(attrs={'class': 'my-same-widht my-same-height'}))
    image = f.ImageField(label='Изображние', required=False, widget=f.FileInput(attrs={'class': 'my-same-widht'}))
    category = f.ModelChoiceField(label='Категория', 
                                    required=False, 
                                    widget=f.Select(attrs={'class': 'my-same-widht'}),
                                    queryset=get_categories_queryset('Category')
                                    )
    price = f.FloatField(label='Цена за товар', required=False, widget=f.NumberInput(attrs={'class': 'my-same-widht'}))
    version_of_product = f.ModelChoiceField(label='Версия', queryset=Version.objects.all(),
                                            required=False, widget=f.Select(attrs={'class': 'my-same-widht'}))

    class Meta:
        model = Product
        exclude = ("last_change_date", "creations_date", "author", "is_published")
    
    def clean_title(self):
        stop_words_list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        cleaned_data = self.cleaned_data.get('title')
        if cleaned_data.lower() in stop_words_list:
            raise f.ValidationError(f'"{cleaned_data}" Недопустимое название для продукта')
        return cleaned_data


class ModeratorUpdateProduct(f.ModelForm):
    description = f.CharField(label='Описание', widget=f.Textarea(attrs={'class': 'my-same-widht my-same-height'}))
    category = f.ModelChoiceField(label='Категория', 
                                    required=False, 
                                    widget=f.Select(attrs={'class': 'my-same-widht'}),
                                    queryset=get_categories_queryset('Category')
                                    )

    class Meta:
        model = Product
        fields = ('description', 'category')

catalog/views.py
from typing import Any
from django.forms.models import BaseModelForm
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from catalog.forms import CreateProduct, ModeratorUpdateProduct
from catalog.models import Product, Version
from django.views import generic as g

from django.contrib.auth import mixins
from django.contrib.auth import decorators as d
from django.views.decorators.cache import cache_page

# Create your views here.

class HomeListView(g.ListView):
    model = Product
    template_name = "catalog/home.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        user = self.request.user
        if user.is_authenticated:
            if user.is_superuser or user.is_staff:
                pass
            else:
                queryset = queryset.filter(is_published=True) | queryset.filter(author=user)
            pass
        else:
            queryset = queryset.filter(is_published=True)
        return queryset


class ContactsCreateView(mixins.LoginRequiredMixin, g.CreateView):
    model = Product
    template_name = "catalog/contacts.html"
    fields = ()
    extra_context = {"title": "Контакты"}
    success_url = "#"

    def form_valid(self, form) -> HttpResponse:
        data = form.cleaned_data
        return super().form_valid(form)
    
    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        name_from_form = request.POST.get("name")
        email_from_form = request.POST.get("email")
        message_from_form = request.POST.get("massage")
        return super().post(request, *args, **kwargs)


class ProductCardView(g.DetailView):
    model = Product
    template_name = "catalog/product.html"
    context_object_name = "product_card"

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        version = Version.objects.all()
        context['version'] = version
        return context
    

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset.filter(pk=self.kwargs["pk"])
        return queryset


class ProductCreateView(mixins.LoginRequiredMixin, g.CreateView):
    model = Product
    template_name = "catalog/product_create.html"
    form_class = CreateProduct
    success_url = reverse_lazy('catalog:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_edit'] = False
        return context

    def form_valid(self, form):
        w = form.save(commit=False)
        w.author = self.request.user
        return super().form_valid(form)


class ProductDeleteView(mixins.LoginRequiredMixin, g.DeleteView):
    model = Product
    template_name = "catalog/product_delete.html"
    context_object_name = 'post_data'
    success_url = reverse_lazy('catalog:home')

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset.filter(pk=self.kwargs["pk"])
        return queryset


class ProductUpdateView(mixins.LoginRequiredMixin, g.UpdateView):
    model = Product
    template_name = "catalog/product_create.html"
    form_class = CreateProduct
    success_url = reverse_lazy('catalog:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_edit'] = True
        return context


class ActiveVersionsListView(g.ListView):
    model = Version
    template_name = 'catalog/versions_list_view.html'
    context_object_name = 'querry'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_active_version = True)
        print(queryset)
        return queryset


@d.permission_required('catalog.change_product')
def change_publish_status(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if product.is_published == True:
        product.is_published = False
    else:
        product.is_published = True
    product.save()
    return redirect(reverse("catalog:home"))


class ModeratorUpdateProduct(mixins.LoginRequiredMixin, mixins.PermissionRequiredMixin, g.UpdateView):
    model = Product
    template_name = 'catalog/moderator_update_product.html'
    success_url = reverse_lazy('catalog:home')
    form_class = ModeratorUpdateProduct
    permission_required = 'catalog.change_product'

catalog/templates/catalog/base.html
<!doctype html>
{% load static %}
<html lang="en">
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
    integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
    integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
    crossorigin="anonymous"></script>

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <title>Skystore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>

<body>
    <div class="d-flex flex-column flex-md-row p-5 px-md-5 mb-1 bg-white border-bottom box-shadow">
        <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
        <nav class="ms-5 md-3">
            {% if not user.is_authenticated %}
            <div class="row">
                <button class="btn btn-sm btn-outline-secondary" type="button"><a class="text-black"
                        href="{% url 'catalog:home' %}">Каталог</a>
                </button>
                <button class="btn btn-sm btn-outline-secondary" type="button"><a class="text-black"
                        href="{% url 'blog_app:all_posts' %}">Блог</a>
                </button>
                <button class="btn btn-sm btn-outline-secondary" type="button"><a class="text-black"
                        href="{% url 'catalog:contacts' %}">Контакты</a>
                </button>
                <button class="btn btn-sm btn-outline-secondary" type="button"><a class="text-black"
                        href="{% url 'user_app:login_user' %}">Войти</a>
                </button>
            </div>
            <div class="row"><a href="{% url 'user_app:register_user' %}">Регистрация нового пользователя</a></div>

            {% else %}

            <div class="row text-start ms-5 md-3">
                <a class="col text-start" style="font: bold; font-size: 6mm;" href="{% url 'user_app:profile_view' %}">{{ user.first_name}}</a>
                <div class="col"><button class="btn btn-sm btn-outline-secondary" type="button"><a class="text-black"
                    href="{% url 'user_app:logout_user' %}">Выйти</a></button>
                </div>
            </div>

            <div class="row ms-5 md-3" style="position: relative; top: 3mm;">
                <div class="col"><button class="btn btn-sm btn-outline-secondary" type="button"><a class="text-black"
                        href="{% url 'catalog:home' %}">Каталог</a>
                    </button>
                </div>
                <div class="col"><button class="btn btn-sm btn-outline-secondary" type="button"><a class="text-black"
                        href="{% url 'blog_app:all_posts' %}">Блог</a>
                    </button>
                </div>
                <div class="col"><button class="btn btn-sm btn-outline-secondary" type="button"><a class="text-black"
                        href="{% url 'catalog:contacts' %}">Контакты</a>
                    </button>
                </div>
                
            </div>
            {% endif %}
        </nav>
    </div>

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Skystore</h1>
        <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
            продать</p>
    </div>

    {% block content %}
    {% endblock %}
    
</body>

</html>

catalog/templates/catalog/base_without_hat.html
<!doctype html>
{% load static %}
<html lang="en">
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
    integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
    integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
    crossorigin="anonymous"></script>

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <title>Skystore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>

<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
        <nav class="ms-5">
            <button class="btn btn-sm btn-outline-secondary" type="button"><a class="text-black"
                    href="{% url 'blog_app:all_posts' %}">Блог</a>
            </button>
            <button class="btn btn-sm btn-outline-secondary" type="button"><a class="text-black"
                    href="{% url 'catalog:home' %}">Каталог</a>
            </button>
            <button class="btn btn-sm btn-outline-secondary" type="button"><a class="text-black"
                    href="{% url 'catalog:contacts' %}">Контакты</a>
            </button>

        </nav>
    </div>

    {% block content %}
    {% endblock %}
    <!-- 
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script> -->
</body>

</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <input class="form-control mb-2" name="name"/>
                        <input class="form-control mb-2" name="email"/>
                        <textarea class="form-control mb-2" name="massage"></textarea>
                        <button type="submit" class="btn btn-primary form-control">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block content %}
<div align="center">
    <div class="container text-center">
        <div class="row mb-4">
            {% if user.is_authenticated %}
                <div class="col">
                    <a href="{% url 'catalog:create_product' %}" type="button"
                        class="btn btn-outline-success">Создать продукт</a>
                </div>
                <div class="col">
                    <a href="{% url 'catalog:active_versions' %}" type="button"
                        class="btn btn-outline-success">Активные версии</a>
                </div>
            {% else %}
            <div class="col">
                <a href="{% url 'catalog:active_versions' %}" type="button"
                    class="btn btn-outline-success">Активные версии</a>
            {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row text-center" style="position: relative; top: 9mm">
        {% for object in object_list %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header"><h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">{{ object.price }}<h3>RUB</h3></h1>
                                {% if user.is_authenticated %}
                                    <button class="btn btn-sm btn-outline-secondary" type="button">
                                        <a class="text-black" href="{% url 'catalog:product' object.pk %}">Просмотреть</a>
                                    </button>
                                    {% if perms.catalog.change_product %}
                                        <button class="btn btn-sm btn-outline-secondary" type="button">
                                            <a class="text-black" href="{% url 'catalog:moderator_update_product' object.pk %}">Изменить (moderator)</a>
                                        </button>
                                    {% endif %}
                                    
                                    {% if object.author|stringformat:"s" == user.email|stringformat:"s" %}
                                        <button class="btn btn-sm btn-outline-secondary" type="button">
                                            <a class="text-black" href="{% url 'catalog:update_product' object.pk %}">Изменить</a>
                                        </button>
                                    {% endif %}
                                        
                                        

                                    {% if perms.catalog.change_product == True or object.author|stringformat:"s" == user.email|stringformat:"s" %}                            
                                        {% if object.is_published %}
                                            <div class="col" style="width: auto; position: relative; top: 5px;">
                                                <button class="btn btn-sm btn-outline-danger" type="button">
                                                    <a class="text-black" href="{% url 'catalog:change_publish_status' object.pk %}">Снять с публикации</a>
                                                </button>
                                            </div>
                                        {% else %}
                                            <div class="col" style="width: auto; position: relative; top: 5px;">
                                                <button class="btn btn-sm btn-outline-danger" type="button">
                                                    <a class="text-black" href="{% url 'catalog:change_publish_status' object.pk %}">Вернуть в публикацию</a>
                                                </button>
                                            </div>
                                        {% endif %}
                                            
                                    
                                    {% endif %}
                                {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

catalog/templates/catalog/moderator_update_product.html
{% extends 'catalog/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/my_styles.css' %}">

    <div class="text text-start">
        <a href="{% url 'catalog:home' %}" type="button" 
        class="btn btn-info mb-5" 
        style="position: relative; left: 5cm;">Назад</a>
    </div>
    <form action method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-2" style="position: relative; left: 3cm;">
        {% for f in form %}
        
        <div class="row col-6 text-start mb-3" style="position: relative; left: 9cm;">
            <div class="col" style="font-size: 6mm;"><label for="{{ f.id_for_label }}">{{ f.label.title }}</label></div>
            <div class="col">{{f}}</div>
        </div>
        <div class="form-error mb-2 text-center"  style="font-size: 6mm; color: brown;">{{ f.errors}}</div>
        {% endfor %}
            
        <div class="m-4">
            <div style="position: relative; left: 20cm; ;">        
                <button href="{% url 'catalog:create_product' %}"
                    class="btn btn-outline-success md-5" type="submit"
                    style="width: 6cm; height: 2cm;">Именить
                </button>
            </div>
        </div>
    </form>
</div>
{% endblock content %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-6">
    <div class="text text-start">
        <a href="{% url 'catalog:home' %}" type="button" class="btn btn-info">Назад</a>
    </div>
</div>

    <div class="card-body px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        {% load mediapath %}
        {% load paragrapher %}
        <div class="card text-start">
            <div class="card-header text-start">
            {% if product_card.author == None %} 
                Автор: Неизвестен
            {% else %} 
                Автор: {{ product_card.author }}
            {% endif%}
            </div>

            <div class="card-body">
                <h5 class="card-title text-start">{{ product_card.title|title }}</h5>
                <p class="card-text text-start">
                    <br><img src="{% mediapath product_card.image %}"
                        width="auto" height="300" alt="Иллюстрация" class="border border-white">
                    {% autoescape off %}
                        <br>{{ product_card.description|paragrapher }}
                    {% endautoescape %}
                    <div class="col">
                        <h3 class="card-text"> Цена {{ product_card.price }} Р. </h3>
                    </div>
                    
                    {% if product_card.version_of_product %}
                    <div class="col">
                        <h3 class="card-text"> Версия {{ product_card.version_of_product }}. </h3>
                    </div>
                    {% endif %}
                </p>
            </div>
        </div>
        </div>

        <footer class="pt-4 my-md-5 pt-md-5 border-top"></footer>
    </div>

    {% endblock %}

catalog/templates/catalog/product_create.html
{% extends 'catalog/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/my_styles.css' %}">

    <div class="text text-start">
        <a href="{% url 'catalog:home' %}" type="button" 
        class="btn btn-info mb-5" 
        style="position: relative; left: 5cm;">Назад</a>
    </div>
    <form action method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-2" style="position: relative; left: 3cm;">
        {% for f in form %}
        
        {% if is_edit %}
        <div class="row col-6 text-start mb-3" style="position: relative; left: 9cm;">
            <div class="col" style="font-size: 6mm;"><label for="{{ f.id_for_label }}">{{ f.label.title }}</label></div>
            <div class="col">{{f}}</div>
        </div>
        <div class="form-error mb-2 text-center"  style="font-size: 6mm; color: brown;">{{ f.errors}}</div>
        {% else %}
        <!-- Условие для того, чтобы поле "Версии появлялось только при редактировании материала" -->
        {% if f.label != form.version_of_product.label %}
        <div class="row col-6 text-start mb-3" style="position: relative; left: 9cm;">
            <div class="col" style="font-size: 6mm;"><label for="{{ f.id_for_label }}">{{ f.label.title }}</label></div>
            <div class="col">{{f}}</div>
        </div>
        <div class="form-error mb-2 text-center"  style="font-size: 6mm; color: brown;">{{ f.errors}}</div>
        {% endif %}
            
        {% endif %}
        {% endfor %}
            
        <div class="m-4">
        <div style="position: relative; left: 20cm; ;">
            {% if is_edit %}            
                <button href="{% url 'catalog:create_product' %}"
                class="btn btn-outline-success md-5" type="submit"
                style="width: 6cm; height: 2cm;">Именить</button>
            {% else %}
                <button href="{% url 'catalog:create_product' %}"
                class="btn btn-outline-success md-5" type="submit"
                style="width: 6cm; height: 2cm;">Создать</button>
            {% endif %}
        </div>
        </div>
    </form>
</div>
{% endblock content %}

catalog/templates/catalog/product_delete.html
{% extends 'catalog/base.html' %}


{% block content %}

<form method="post">{% csrf_token %}
    <div class="col">
        <div class="container justify-content-center">
            <h2 align="center">Вы, действительно, хотите удалить запись?</h2>
            <div align="center"><h5>{{ post_data.title }}</h5></div>
            <h1> </h1>
        </div>
    </div>
    {{ form }}
    <div class="container text-center">
        <div class="row justify-content-center">
            <input type="submit" class="btn btn-outline-danger"
                value="Подтвердить">
            <a type="button" class="btn btn-outline-success"
                href="{% url 'catalog:home' %}">Отменить</a>
        </div>
    </div>
</form>

{% endblock content %}

catalog/templates/catalog/version_create.html
{% extends 'catalog/base.html' %}


{% block content %}
    
{% endblock content %}
    